server:
  port: 8080

  servlet:
    ### UTF-8 ###
    encoding:
      force: true # UTF-8이 SpringBoot 2.x.x 에서는 기본이다.

spring:
  config:
    group:
      dev: # dev프로필로 프로젝트를 실행시키면 dev yml이 활성화 됩니다.
        - dev
      test: # test프로필로 프로젝트를 실행시키면 test yml이 활성화 됩니다.
        - test

  ### Redis 설정 ###
  redis:
    image: redis:latest
    host: localhost
    port: 6379

  #Message 설정
  messages:
    basename: i18n/exception
    encoding: UTF-8

### Security ###
security:
  jwt:
    token:
      secretKey: afsdasfdASAWRSasgdvFTUJARGtasdfSRTJSRTEQR14asdfVA

### Sms ###
sms:
  api:
    apikey: NCS7NY4SNRLQKWGE
    apiSecret: GE5VDUZPVLG9RB9QGDST4COFKC1UN7YJ